FROM fedora:38
LABEL maintainer "Angelo Claudio Re <rhacrsse@linux.com>"

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    HOME=/home/user

COPY Dezor-v1.2.9-x86_64.AppImage /usr/local/bin/

RUN useradd --create-home --home-dir $HOME user && \
    chown -R user:user $HOME && \
    chown -R user:user /usr/local/bin && \ 
    chmod 0744 /usr/local/bin/Dezor-v1.2.9-x86_64.AppImage && \
    yum install -y pipewire pipewire-alsa alsa-utils && \
    yum install -y nss atk at-spi2-atk cups libdrm gtk3 mesa-libgbm && \
    cd /usr/local/bin/; ./Dezor-v1.2.9-x86_64.AppImage  --appimage-extract && \
    chown -R user:user /usr/local/bin/squashfs-root

WORKDIR $HOME
USER user

CMD ["/usr/local/bin/squashfs-root/AppRun"]
